#!/bin/sh

if [ `which yum 2>/dev/null` ]; then
	yum install -y epel-release
	yum update -y
	yum install -y tcsh freecolor nano screen ipcalc wget tmux git htop mtr eza pwgen bind-utils
	# TODO: add "grc"

elif [ `which apt 2>/dev/null` ]; then
	apt install -y tcsh nano screen ipcalc wget tmux grc git htop mtr-tiny
	# TODO: add "freecolor", "eza", bind tools, pwgen

elif [ `which pkg 2>/dev/null` ]; then
	pkg install -y eza freecolor nano screen ipcalc wget tmux grc htop btop mtr-nox11 bind-tools pwgen bsdinfo ncdu2

else
	echo "Unknown package manager" 1>&2
	exit 1
fi
