#
#	This file is required by the ISC DHCP client.
#	See ``man 5 dhclient.conf'' for details.
#
#	In most cases an empty file is sufficient for most people as the
#	defaults are usually fine.
#

request
	host-name,

	subnet-mask,
	broadcast-address,

	routers,
	static-routes,
	classless-static-routes,

	domain-name-servers,
	domain-name,
	domain-search,

	interface-mtu,

	ntp-servers,
	time-offset
;
